package main

import (
	"bytes"
	"fmt"
	"html/template"
	"os"
	"strings"
	"time"
)

const shiftHTMLTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Shift Participation Report — {{.GeneratedAt.Format "January 2, 2006"}}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a2e; background: #f8f9fa; padding: 2rem; }
  header { text-align: center; margin-bottom: 2rem; padding-bottom: 1rem; border-bottom: 3px solid #c41e3a; }
  header h1 { font-size: 1.8rem; color: #c41e3a; }
  header p { color: #666; margin-top: 0.25rem; }
  section { background: #fff; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  section h2 { font-size: 1.25rem; color: #c41e3a; margin-bottom: 1rem; border-bottom: 2px solid #eee; padding-bottom: 0.5rem; }
  section p.summary { color: #666; margin-bottom: 0.75rem; }
  table { width: 100%; border-collapse: collapse; }
  th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #eee; }
  th { font-weight: 600; color: #555; font-size: 0.85rem; text-transform: uppercase; }
  td { font-size: 0.95rem; }
  td.empty { color: #ccc; }
  footer { text-align: center; color: #999; font-size: 0.85rem; margin-top: 2rem; }
  @media print { body { padding: 0; } section { box-shadow: none; border: 1px solid #ddd; } }
</style>
</head>
<body>
<header>
  <h1>Shift Participation Report</h1>
  <p>Generated {{.GeneratedAt.Format "January 2, 2006"}}</p>
</header>

{{range .Periods}}
<section>
  <h2>{{.Label}} &mdash; {{.Range.Start.Format "Jan 2, 2006"}} to {{.Range.End.Format "Jan 2, 2006"}}</h2>
  <p class="summary">{{.TotalCalls}} total calls</p>
  {{if .TotalCalls}}
  <table>
    <tr>
      <th rowspan="2">User</th>
      {{range .Shifts}}
      <th colspan="2">{{.}}</th>
      {{end}}
    </tr>
    <tr>
      {{range .Shifts}}
      <th>O/S</th><th>N/S</th>
      {{end}}
    </tr>
    {{range .UserRows}}
    <tr>
      <td>{{.UserName}}</td>
      {{range .Cells}}
      <td>{{if .OnSceneCount}}{{printf "%.1f" .OnScenePct}}% ({{.OnSceneCount}}){{else}}<span class="empty">&mdash;</span>{{end}}</td>
      <td>{{if .NotOnSceneCount}}{{printf "%.1f" .NotOnScenePct}}% ({{.NotOnSceneCount}}){{else}}<span class="empty">&mdash;</span>{{end}}</td>
      {{end}}
    </tr>
    {{end}}
  </table>
  {{end}}
</section>
{{end}}

<footer>
  Generated by Emergency Networking Shift Participation Report
</footer>
</body>
</html>`

// userRowTemplate holds a user and their cells for one period section.
type userRowTemplate struct {
	UserName string
	Cells    []ShiftUserRecord
}

// periodTemplate holds data for one period section of the HTML.
type periodTemplate struct {
	Label      string
	Range      struct{ Start, End time.Time }
	TotalCalls int
	Shifts     []string
	UserRows   []userRowTemplate
}

// htmlPageData is the top-level data for the HTML template.
type htmlPageData struct {
	GeneratedAt time.Time
	Periods     []periodTemplate
}

func saveShiftHTML(periods []PeriodResult) (string, error) {
	var pt []periodTemplate
	for _, pr := range periods {
		rows := pivotToUserRows(pr.Shifts, pr.Records)
		var urt []userRowTemplate
		for _, r := range rows {
			urt = append(urt, userRowTemplate{UserName: r.UserName, Cells: r.Cells})
		}
		pt = append(pt, periodTemplate{
			Label:      pr.Label,
			Range:      struct{ Start, End time.Time }{pr.Range.Start, pr.Range.End},
			TotalCalls: pr.TotalCalls,
			Shifts:     pr.Shifts,
			UserRows:   urt,
		})
	}
	data := htmlPageData{
		GeneratedAt: time.Now(),
		Periods:     pt,
	}

	tmpl, err := template.New("shift-report").Funcs(template.FuncMap{
		"displayName": func(name string) string {
			return strings.ReplaceAll(name, "_", " ")
		},
	}).Parse(shiftHTMLTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	filename := fmt.Sprintf("shift_participation_%s.html", time.Now().Format("2006-01-02_150405"))
	if err := os.WriteFile(filename, buf.Bytes(), 0644); err != nil {
		return "", fmt.Errorf("write file: %w", err)
	}
	return filename, nil
}
