package main

import (
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

func saveShiftPDF(periods []PeriodResult) (string, error) {
	pdf := gofpdf.New("P", "mm", "Letter", "")
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)

	pdf.AddPage()
	pageW, _ := pdf.GetPageSize()

	// Red header bar — matches existing report style
	pdf.SetFillColor(196, 30, 58)
	pdf.Rect(0, 0, pageW, 18, "F")
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 14)
	pdf.SetY(4)
	pdf.CellFormat(0, 9, "Shift Participation Report", "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 8)
	pdf.CellFormat(0, 5, fmt.Sprintf("Generated %s", time.Now().Format("January 2, 2006")), "", 1, "C", false, 0, "")

	pdf.SetTextColor(26, 26, 46)
	pdf.SetY(24)

	for _, pr := range periods {
		// Section header
		pdf.SetFont("Helvetica", "B", 12)
		pdf.SetTextColor(196, 30, 58)
		pdf.CellFormat(0, 8, fmt.Sprintf("%s (%s – %s)", pr.Label,
			pr.Range.Start.Format("Jan 2, 2006"),
			pr.Range.End.Format("Jan 2, 2006")), "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(102, 102, 102)
		pdf.CellFormat(0, 6, fmt.Sprintf("%d total calls", pr.TotalCalls), "", 1, "L", false, 0, "")
		pdf.Ln(3)

		if pr.TotalCalls == 0 || len(pr.Records) == 0 {
			pdf.SetFont("Helvetica", "I", 10)
			pdf.SetTextColor(136, 136, 136)
			pdf.CellFormat(0, 6, "(no calls in period)", "", 1, "L", false, 0, "")
			pdf.Ln(4)
			continue
		}

		// Build table
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetTextColor(26, 26, 46)

		// Calculate column widths dynamically
		userColW := 50.0
		shiftColW := (pageW - 30 - userColW) / float64(len(pr.Shifts))
		if shiftColW > 40 {
			shiftColW = 40
		}

		// Header row
		pdf.SetFillColor(240, 240, 240)
		pdf.CellFormat(userColW, 7, "User", "1", 0, "L", true, 0, "")
		for _, shift := range pr.Shifts {
			pdf.CellFormat(shiftColW, 7, safeText(shift), "1", 0, "C", true, 0, "")
		}
		pdf.Ln(-1)

		// Data rows
		pdf.SetFont("Helvetica", "", 8)
		userRows := pivotToUserRows(pr.Shifts, pr.Records)
		for _, row := range userRows {
			// Check for page break
			if pdf.GetY() > 250 {
				pdf.AddPage()
				// Repeat header on new page
				pdf.SetFillColor(240, 240, 240)
				pdf.SetFont("Helvetica", "B", 8)
				pdf.CellFormat(userColW, 7, "User", "1", 0, "L", true, 0, "")
				for _, shift := range pr.Shifts {
					pdf.CellFormat(shiftColW, 7, safeText(shift), "1", 0, "C", true, 0, "")
				}
				pdf.Ln(-1)
				pdf.SetFont("Helvetica", "", 8)
			}
			pdf.CellFormat(userColW, 6, safeText(row.UserName), "0", 0, "L", false, 0, "")
			for _, cell := range row.Cells {
				text := "—"
				if cell.CallCount > 0 {
					text = fmt.Sprintf("%.1f%% (%d)", cell.Pct, cell.CallCount)
				}
				pdf.CellFormat(shiftColW, 6, text, "0", 0, "C", false, 0, "")
			}
			pdf.Ln(-1)
			// Draw subtle row separator
			pdf.SetDrawColor(230, 230, 230)
			y := pdf.GetY()
			pdf.Line(15, y, pageW-15, y)
			pdf.SetY(y)
		}
		pdf.Ln(4)
	}

	// Footer
	pdf.SetTextColor(153, 153, 153)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetY(-20)
	pdf.CellFormat(0, 10, "Generated by Emergency Networking Shift Participation Report", "", 0, "C", false, 0, "")

	filename := fmt.Sprintf("shift_participation_%s.pdf", time.Now().Format("2006-01-02_150405"))
	if err := pdf.OutputFileAndClose(filename); err != nil {
		return "", fmt.Errorf("write pdf: %w", err)
	}
	return filename, nil
}

// safeText replaces characters that gofpdf can't render.
func safeText(s string) string {
	// gofpdf uses a limited encoding; replace problematic chars.
	out := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		if s[i] < 128 {
			out = append(out, s[i])
		} else {
			out = append(out, '?')
		}
	}
	return string(out)
}
